#cloud-config
users:
  - name: appuser
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - sh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQClgtkQ+sQuuE3gfNUIIn0Wxt6AVwNbtNPhn3u52mIWgl1ALbFbh4jm1gFCc0GOaxjoA3WcrukFVClMq1CORBAUlRlZXgurHByxkvfq4Z1FLLoS1NB6HAgC/t/2sWdEHo+UhTAiyosEQH1gS708rHtoH7IWFgxakmS1PoS7g0DdgPCFLwjTtDlkk2PVJYRTXKFhOFQWKfaysU0K2hJBWyi4qsgWLWXJjb58U6AbZ5HnzG1KeppvjTxr4W6sUK3B>


write_files:
 - path: /home/startup_script.sh
   permissions: '0555'
   content: |
     #!/bin/sh
   apt update
   apt install -y ruby-full ruby-bundler build-essential
   apt install -y mongodb
   systemctl start mongodb
   systemctl enable mongodb
   cd /home/yc-user
   apt -y install git
   git clone -b monolith https://github.com/express42/reddit.git
   cd reddit && bundle install
   puma -d
runcmd:
 - [ bash, /home/startup_script.sh ]
