# tasks file for install db

- name: Install mongodb
  apt:
    name: mongodb
    state: present
    update_cache: yes

- name: Remove packages
  apt:
    autoclean: yes

- name: Remove dependencies
  apt:
    autoremove: yes

- name: Enable
  systemd:
        name: mongodb
        enabled: yes
