- name: Install packages for app base
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'ruby-full', 'ruby-bundler', 'build-essential', 'git']
    state: present
    update_cache: true
  retries: 5
  delay: 20
  tags: ruby

- name: Remove useless packages from the cache
  apt:
    autoclean: true
  tags: ruby

- name: Remove dependencies that are no longer required
  apt:
    autoremove: true
  tags: ruby
